#!/bin/sh

cat $1 | html-minifier --collapse-boolean-attributes --collapse-inline-tag-whitespace --collapse-whitespace \
        --html5 --decode-entities --minify-css --minify-js --remove-comments --remove-script-type-attributes \
        --remove-optional-tags --remove-style-link-type-attributes --use-short-doctype --remove-attribute-quotes\
        --remove-redundant-attributes -o "$2";

