#!/bin/bash

hour=$(date +"%l");
min=$(date +"%M" | sed 's/^0//');
ampm=$(date +"%p");

if (( $min > 0 )); then
    spoken_time="It's $hour $min $ampm";
else
    spoken_time="It's $hour'o clock $ampm";
fi;

echo $spoken_time | espeak --stdin -v mb-us1 -p 60 -s 130;


